apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tce-repo
  namespace: tanzu-package-repo-global
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tce/main:0.10.2
