---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: auth-infra
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./config/mgmt/build/auth-infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: age-key
