---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: auth-config
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./config/mgmt/build/auth-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: auth-infra
    - name: secure-ingress-config
  decryption:
    provider: sops
    secretRef:
      name: age-key
