---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-webhook
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./config/flux-system-webhook
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
