---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secure-ingress-config
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./config/secure-ingress-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: secure-ingress-infra
