apiVersion: v1
kind: Service
metadata:
    labels:
        app: pinniped-supervisor
    name: pinniped-supervisor
    namespace: pinniped-supervisor
spec:
    ports:
        - port: 8080
          protocol: TCP
    selector:
        app: pinniped-supervisor
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUXVUWVQyNkpudEF5NDR3
            WnRVcTA3N0RLSTVjZ2QxdHFsd2FaVC91ZzFvCkk3cVJNWnl5QndUZTMxTHc2Q0tW
            RnBTMEJ3VE11aURKUEdKWTRZUXVlOFUKLS0tIDZlUWRmZWNveDI3OFRDa1BoTmdD
            Y0t5aGtVQlpwSXd0VGx0WkxxaDIrMzAK+12Jg5Pxl9SIYhSDTsvMW3zzUzZKJOQT
            Uv2LsAQV/wPiRQJUKKHcikbbga6Umdywrr2qrgiuU74jLLcAv6RGlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:i7OylJSTUTTzzPzquu8ZbMijM5OP0Q+lZ4TR6imFudL1tQbJ+7k4v/XqVV+CkO1lWQb4nGCP050KtemL6q7yw1nv+TCbSHc0PQNDy6/N3tFjtL3O2D1sRu37KNkYgl5yXzZlgkBs+kQpYgLM/3xhccTwLxzxHEcln69lkP+tSTs=,iv:s9F3d8XK424aJsboBJ10Tb8GGchILs1fzCeg/POre4M=,tag:4SZE4dsh3Pu5AW1QFtyH5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: pinniped-supervisor
    namespace: pinniped-supervisor
    annotations:
        ingress.kubernetes.io/force-ssl-redirect: "true"
        projectcontour.io/tls-cert-namespace: secure-ingress
spec:
    tls:
        - hosts:
            - pinniped.yaml.tv
          secretName: wildcard-yaml-tv
    rules:
        - host: pinniped.yaml.tv
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: pinniped-supervisor
                        port:
                            number: 8080
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUXVUWVQyNkpudEF5NDR3
            WnRVcTA3N0RLSTVjZ2QxdHFsd2FaVC91ZzFvCkk3cVJNWnl5QndUZTMxTHc2Q0tW
            RnBTMEJ3VE11aURKUEdKWTRZUXVlOFUKLS0tIDZlUWRmZWNveDI3OFRDa1BoTmdD
            Y0t5aGtVQlpwSXd0VGx0WkxxaDIrMzAK+12Jg5Pxl9SIYhSDTsvMW3zzUzZKJOQT
            Uv2LsAQV/wPiRQJUKKHcikbbga6Umdywrr2qrgiuU74jLLcAv6RGlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:i7OylJSTUTTzzPzquu8ZbMijM5OP0Q+lZ4TR6imFudL1tQbJ+7k4v/XqVV+CkO1lWQb4nGCP050KtemL6q7yw1nv+TCbSHc0PQNDy6/N3tFjtL3O2D1sRu37KNkYgl5yXzZlgkBs+kQpYgLM/3xhccTwLxzxHEcln69lkP+tSTs=,iv:s9F3d8XK424aJsboBJ10Tb8GGchILs1fzCeg/POre4M=,tag:4SZE4dsh3Pu5AW1QFtyH5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
