apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
    name: my-supervisor-authenticator
spec:
    issuer: https://pinniped.yaml.tv
    audience: my-unique-cluster-identifier-31249-25880
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZDBqR2wzK0Z6d1A0SUNr
            NlNzelhsU1ovNDJHenc0OVZwdVZKM1VmdlUwCkw4VEloNmQzRS9JcWtQNHg3WGFP
            bWtvRU93VzJQREtPQzlqVEdkaUdHZzgKLS0tIDZ0TzY1TEFOTHQvNVVsYXY4VHdu
            eVZmT3N3M000b3QzTDcvMnVUYVFzdk0KPH2Wa1pH6+wN1dqYYHJdJcln9BGU3CKy
            ynmBZSGE5lr8aQ0Uhfpv2tmnftISn1v1k0b3SIsySOBLNwLDZ05OYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T08:34:50Z"
    mac: ENC[AES256_GCM,data:8PIwB7e29IVikkwuwpn1CzbmCRzndqYvmengqCsDQGeufwywdb1hg6MS3djgOYNUxL0MRA4Cba2B75doWgOqIMbvSvFWBMwgxihxHI+IraY+U0vcRTdTkZLhNe/ZZ+YBa/Q68jV0gi3+P4loWl7BU99hjBb223z5A7DDdBr5R8E=,iv:WSyPLbNj5PLDyURbVQMzvzDp4nfUpXXfNLM2pjvVvcM=,tag:X1SlVFuyjvrPUZn7XC76ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
