apiVersion: v1
kind: Secret
metadata:
    name: dex-client-credentials
    namespace: pinniped-supervisor
type: secrets.pinniped.dev/oidc-client
stringData:
    clientID: ENC[AES256_GCM,data:B+5lAxBIS6ZhmhD1bA==,iv:RhgGIxHMihiHm28uWhAYsVfCzzSSKZAVpUIeoVMXLQM=,tag:0qP7xFputseGO1wGmD1x5g==,type:str]
    clientSecret: ENC[AES256_GCM,data:RXUyPBXUyqg5UC1OAdPV2I0xrrUwL2ZltxmRUFYbb+o=,iv:3jBJgK5t6hiV6yJEfFepsVGGdAYZ+Wx/vEairaU14Fs=,tag:ioWPtQowtBpKpjPhYu/d8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc3ZTb1ExRVhLMmd6WE1K
            VWlVWWR4a2hmSXVQTDlIUUVkSjliRlZNV0RrCk40bjdCKzZyWVdnSUdRZjgzSElW
            OFFxcXExK0E1SmFOQ1JrWVpQNHpRTFUKLS0tIFVOQ0FERFZwQkRWY3oyRzR1eHpS
            RUxJSnM2ZC9ydnBQQ3gzakhhNXBiaTQKZ2VWZ7K9FiHy6z0anPKcCspzAPbwAlZv
            occJ2eDhsM82hu6z/IIuXcKutzZhvRJDR3FmfFP1e7/kUXS7P7J5Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:eiwNBLUbI+67JOw9YdO2cqVH6X7ZYiAcLNzm98J63peHmF0QjT4WLljed2T3CArDsj7enjR/2De7Aelry5xsJuWUmLIaPCFAMcEG7gzdvy3Mq5xrMBckOUb4SQ6WJFSvGweSIyO5m/+onMJj3uR6MKYYKke9P4kUTxk427s7J2g=,iv:AIa/i0qfBCaf0NnQT3BdVTyzOcs6lslqkX7S95r0MuE=,tag:XVgTu5DSV9gAc4sn7XhQvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
    name: dex
    namespace: pinniped-supervisor
spec:
    issuer: https://dex.yaml.tv
    authorizationConfig:
        additionalScopes:
            - offline_access
            - groups
            - email
        allowPasswordGrant: false
    claims:
        username: email
        groups: groups
    client:
        secretName: dex-client-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc3ZTb1ExRVhLMmd6WE1K
            VWlVWWR4a2hmSXVQTDlIUUVkSjliRlZNV0RrCk40bjdCKzZyWVdnSUdRZjgzSElW
            OFFxcXExK0E1SmFOQ1JrWVpQNHpRTFUKLS0tIFVOQ0FERFZwQkRWY3oyRzR1eHpS
            RUxJSnM2ZC9ydnBQQ3gzakhhNXBiaTQKZ2VWZ7K9FiHy6z0anPKcCspzAPbwAlZv
            occJ2eDhsM82hu6z/IIuXcKutzZhvRJDR3FmfFP1e7/kUXS7P7J5Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:eiwNBLUbI+67JOw9YdO2cqVH6X7ZYiAcLNzm98J63peHmF0QjT4WLljed2T3CArDsj7enjR/2De7Aelry5xsJuWUmLIaPCFAMcEG7gzdvy3Mq5xrMBckOUb4SQ6WJFSvGweSIyO5m/+onMJj3uR6MKYYKke9P4kUTxk427s7J2g=,iv:AIa/i0qfBCaf0NnQT3BdVTyzOcs6lslqkX7S95r0MuE=,tag:XVgTu5DSV9gAc4sn7XhQvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
