#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: github-client
  namespace: dex
stringData:
  client-id: #@ data.values.github_client_id
  client-secret: #@ data.values.github_client_secret
