apiVersion: v1
kind: Secret
metadata:
    name: github-client
    namespace: dex
stringData:
    client-id: ENC[AES256_GCM,data:Nqj5BdIZhutb9KxR+uaBZ1vFByw=,iv:Bf36F8HWGN4WCeZKC24D0IWaM5gUcwV/vkufKYwzOI4=,tag:aqSHo45Ilu0wExwXj/RuRA==,type:str]
    client-secret: ENC[AES256_GCM,data:pvHlDz8qE4+W8UF0Nlh1ItEB+/K9WTEajHcIO5Ql5r+8S5v63ubyvA==,iv:Iq2/92bcjDjR+7uDINfpuzqhtuYm6gWX2yoAmAifT3M=,tag:U3QzaPlYp2X5rC20iE70Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMWs5LzhDUjNJLzhMSnVL
            enAzQTMwUUUvTmJrNURWYi9lWFhnU2hmd2lBCmVpa0ZCN3BGWkNEVzh1TW5IOXIv
            OERXSDE2Ri9pY0VpTlkwR2dkQzNFck0KLS0tIGYwK25ZU3ArbDZmZHNRd0FkK1lo
            MTh0SnlvWXB1OXlHUWlSOWt3Z01CNVUKIlHq+E8dWafiSrccaYXSfyntyRF8CzW5
            L7JK51QoBqkesoxQ+/PE4KnWWI9C1jo3u4XjGzidzXK/jrOMtI+XtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T08:34:50Z"
    mac: ENC[AES256_GCM,data:Dg6Sm5ZpD/Z5TMcGS/5ZN9NhgbwPtUk7wXDuA/wwEE9r3TRScWXvvWPmBFLHTp3XUd987cg7FLVyBcuyqAMl+Z9FwP9FdY7201BXRehfXuERok92AuwE6Go+1QF1pe65dkIS1ptzHPiqJDZJ5Mv0wUr7ZWHTMOAXedBiIgUNcJ4=,iv:s/3eHs49jpsl+C2Eqi34lMx2xla/Fe3TdvsHJr43lxQ=,tag:zH+oWMczqmlElkX70AFEyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
