apiVersion: v1
kind: Secret
metadata:
    name: github-client
    namespace: dex
stringData:
    client-id: ENC[AES256_GCM,data:PiCnU5vVejTso4aEBPuyiXrE/Yg=,iv:Av7zhYt4osib6HohStwev3+Cyu/otQ2d0WnxGW7RhFc=,tag:ed9/nJ4Xnsx3KHhyjy2fjw==,type:str]
    client-secret: ENC[AES256_GCM,data:g88fjXP4qnzfsRt7rZ+A/3j0WcV2wnPpauijtuM/2MVfoHEtaVocQA==,iv:nWogtY82x+SWpAFd0gBxGrKX+GrkwmNkg7ONkcADDnA=,tag:EMN1vrXiH2IZ3DJTzzO8pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCK1AyNmNPQTgrY0JRVzZK
            YUFwallBVC9HV1M4SDU1OU56R1FVOU1Bb0U0CmZUSUcwQzlIN3lqU29EWk00cGlj
            WnZRNjdlQXI4bExXbGw1YWMwcmFRN3cKLS0tIGg0SGtJN2lPbkZCRzc1ekpEMllE
            T3RtdUwvSkVDVHUzak14aG5DM09FVUkKaMfKgIahuSOdk94M+vNAXbsTyCuuPRwt
            FK1Yk0JnUycKNeSivqrkwVsZw8Oz8DfzQO8csGp13cqOKOPuTtFOZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T10:07:19Z"
    mac: ENC[AES256_GCM,data:JxOGspvBBdqPWlVYxooGMFlVpCciM09ANTI7vV7VI0sZInR5Tqj0KMXkguaIH0CCSeDaPR0e/jXLSaHyNYLG70oD/F5JvY0mhx5o8/jknT69np7n7j9d7jWBN7p4QGMXsfDVMmYqZRKymzy+kByXK7n6jmv25D0QCYAFxYiYVQo=,iv:LUq3WUE6W2UxMersvX00GgEj7E4UrqBkNTdoyb7IR9k=,tag:6ftvb/ODCX1i1MnjmBrk6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
