apiVersion: v1
kind: Secret
metadata:
    name: github-client
    namespace: dex
stringData:
    client-id: ENC[AES256_GCM,data:peBuv52sCkOx/oaJwZPoVzjIeYM=,iv:eN8Twj3VfDY7G7sJbKfLq4pNCp2DMNCvaOepvG75UNQ=,tag:Lvfiuvwhqbs8NDZoARobSA==,type:str]
    client-secret: ENC[AES256_GCM,data:YVoxkYIyxkDLrrGso6LYoHC2lG/dI+e+s852R60UJCSp6UjmYcDj1w==,iv:QH/vln3dAj0rIQ4rbo0pzeyDF1oR+ci8qsOiS78yJyw=,tag:HL6tfcv2uXC5wbyPYU5JSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneUVIK053azhGZFNHWU5j
            R0VLam8xWU5GdnVpT2xOTkJCektjQVkvU0MwCmVhS0NZNXVBNHNka2U5STNiNmZO
            L2dlam1tYkp5Ni9qTWpMQlJWUWlkMWMKLS0tIFYyTTdyZCszVFVwM1FlVjVuOEFC
            cFQxNUd1Q3BoQ2ltbFVBNXd2YlhoOVkKMDWWZWmF0jILu/WaP9CriLJDcYeu0eMY
            tv/+8D36D/fGtz0tPkw70CrlWacco3vf6A2fvw5FejoSLMJ8ciYuzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:g3JviMnHTs4Aw860SMMSGU46ltFI4I3Z1LMKcgv4YqChNmS/XkK2MD+XPjk/HN/aGpC8Le8FyivFev1MbDGLAME/ns15UtC1NCi4LSg82zb+HWBoUm+fEZw+XGxShexrD4zyatt1aoUL3x18AMv2SA66YK8R30PwuFCmTIbm2LA=,iv:+TH+n9MSYthd/zavrPfcf7vAp3eZLW9z3k9Mk2477Yg=,tag:gl7I/+37TDEh0X9xB/L1Tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
