apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: dex
    namespace: dex
    annotations:
        ingress.kubernetes.io/force-ssl-redirect: "true"
        projectcontour.io/tls-cert-namespace: secure-ingress
spec:
    tls:
        - hosts:
            - dex.yaml.tv
          secretName: tls
    rules:
        - host: dex.yaml.tv
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: dex
                        port:
                            name: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM1UvNWlWdUtXMks1Wi9I
            dmlXU3RmRytld1hZL3U3cGlGcklzeXNlcEhjCkJmcTNnL21pV1BObkRtOWdqNkNq
            bk5SSm9SSVpuU1BTbHFZRDF1QjNpNFUKLS0tIE5vY2R5WGZhay96bVF1cTlTQi9i
            aG5PVXMxdXdFMW9wTW5IQnB4eUR1em8KmqGMcK6AJfI9nuJ+Tdvmxx2tKmPqofqB
            LHnniLDMWlXP96JR8a3Xg0HDq0S11sH8Jcporf7sfP8TDLr3vFuQgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T08:34:50Z"
    mac: ENC[AES256_GCM,data:XLt+OWjQ+/Ho0AkN+qC7UKhH6jEK8/lqWb8GIszMFmxMpYq3+xrjbUftEky8tZDw1khsjGdBwDWKm7fatMueZ28LCMJFZi8ujEsNCcfKTXz9ty1m16IddF5wT5VUHdziedJdMVd6HofTMLZx9LyeJi4P4Zoy7YmRT71UvPE7BCI=,iv:X56hn4jgdoqFD7HJsH7bQUw4XFn0ecGeOqXJDfsuM+k=,tag:B+LnF4KR9CLXQbgZKbbGqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
