apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: dex
    namespace: dex
    annotations:
        ingress.kubernetes.io/force-ssl-redirect: "true"
        projectcontour.io/tls-cert-namespace: secure-ingress
spec:
    tls:
        - hosts:
            - dex.yaml.tv
          secretName: wildcard-yaml-tv
    rules:
        - host: dex.yaml.tv
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: dex
                        port:
                            name: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWW1rdjAvUHpzRTlxSTFI
            OW14cUpnbDZ3Vmp3dUFGV2ZERFNhQnVUeVNvCldwV292YUdKbnRiWDVRcU4raDV4
            TGpaZWNaTmZYOVkzcEI3NThYV3pKUGMKLS0tIE5ucGkrWmsyZm5MM0NhZjJRcXhH
            TXZmT014QXByMzljQjFnYTRKSUVoS3cKLOEobPWYN1Djet6QR+JvUnXjBx5qFypo
            B9yhf/Rwo/hx+tiBwseCEvGjtBIiMOmcchx2ZcL2e1dXHVHkpA6bxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T11:25:01Z"
    mac: ENC[AES256_GCM,data:ueJrbbrG8+/C0duI5j+Ahjir6L2i+tPksuwh0fTV3PxiNYGSagb3oUPtky72j4G5M3c+0bdyGCVGNhje4MauMTBQ/Y+68v4Vg8S4uoWiyogmYXLPHLzSZ6GRaRxac2F7xpEOdYqCuzCjY4h+6aEzgg5kC7nDilgnAAywZbCC4vw=,iv:GXaT8ZecvdDMIfs0uu5A3LAfB1sTawFCPH3dHw/ifZg=,tag:P3p6k3VnPW5Q+J8ICD2Ifw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
