apiVersion: v1
kind: Namespace
metadata:
    name: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGVDQXZva3Z3YlROZFhj
            SWhRaWRwSnVHMWlSSDIwMW1OZ011YmUyZTN3CnBJTnZJRWkvWUQxOWtwVm1MTGdB
            Z05VSTdyck5iejQxakZjakVEVEorS2sKLS0tIDQ3VXhLcW5JQUF0V2FUZ0JuZG91
            RVdoT0g1aGV3d1IrL2ZxdzBKTWVhM28Kf6xeA1sBFjC8d1nCFVHYxkRndR8pN0z4
            Sg1XvK4loM8956wjbfaA4NzQmejnuP2oGxn6ICyESE5cxDFjEi8Inw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:P7txWrASQTpXhdX650SJQaqm30mp8o6iqW841UAcwaM5bRPiaYJaaWCsvY0abFc7Kdu8tK1q8+uJgDraS5G/O5RtNrcdgTxmn+xFkLrGctRrkD/NDEKPdr+7Nk4I4osBcesHHk71Rc0BSW9FxJDlnAk6ahKTMWJB3TN9iI2b7bI=,iv:3d6hq8DPFO6SAqbBOX6gfmZ3HtBJwUjE3ZhaTBxHX60=,tag:Y31VSh6yuRoUYa7PMwHs4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: dex
    name: dex
    namespace: dex
spec:
    replicas: 3
    selector:
        matchLabels:
            app: dex
    template:
        metadata:
            labels:
                app: dex
        spec:
            serviceAccountName: dex
            containers:
                - image: ghcr.io/dexidp/dex:v2.30.0
                  name: dex
                  command:
                    - /usr/local/bin/dex
                    - serve
                    - /etc/dex/cfg/config.yaml
                  ports:
                    - name: https
                      containerPort: 5556
                  volumeMounts:
                    - name: config
                      mountPath: /etc/dex/cfg
                  env:
                    - name: GITHUB_CLIENT_ID
                      valueFrom:
                        secretKeyRef:
                            name: github-client
                            key: client-id
                    - name: GITHUB_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                            name: github-client
                            key: client-secret
                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: 5556
                        scheme: HTTP
            volumes:
                - name: config
                  secret:
                    secretName: dex
                    items:
                        - key: config.yaml
                          path: config.yaml
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGVDQXZva3Z3YlROZFhj
            SWhRaWRwSnVHMWlSSDIwMW1OZ011YmUyZTN3CnBJTnZJRWkvWUQxOWtwVm1MTGdB
            Z05VSTdyck5iejQxakZjakVEVEorS2sKLS0tIDQ3VXhLcW5JQUF0V2FUZ0JuZG91
            RVdoT0g1aGV3d1IrL2ZxdzBKTWVhM28Kf6xeA1sBFjC8d1nCFVHYxkRndR8pN0z4
            Sg1XvK4loM8956wjbfaA4NzQmejnuP2oGxn6ICyESE5cxDFjEi8Inw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:P7txWrASQTpXhdX650SJQaqm30mp8o6iqW841UAcwaM5bRPiaYJaaWCsvY0abFc7Kdu8tK1q8+uJgDraS5G/O5RtNrcdgTxmn+xFkLrGctRrkD/NDEKPdr+7Nk4I4osBcesHHk71Rc0BSW9FxJDlnAk6ahKTMWJB3TN9iI2b7bI=,iv:3d6hq8DPFO6SAqbBOX6gfmZ3HtBJwUjE3ZhaTBxHX60=,tag:Y31VSh6yuRoUYa7PMwHs4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
kind: Secret
apiVersion: v1
metadata:
    name: dex
    namespace: dex
    annotations:
        kapp.k14s.io/versioned: ""
data:
    config.yaml: ENC[AES256_GCM,data:At56ZsF4U+xL4PKl7pEnYAO2ar5xcrF9klIQW/aXGIzWfOIaAsYB+igvH0ToYeTWrqORvSWOTZpwUYGEd63lXNHkAXEk1IIVgK0a3UiITV+Cf7E+oqdeS51a1B2i70CCf8FebIlmFJAIPTLBIc7+dj06wfB3BGnD7kRbLw66Vcu/y4nIsm+PDOJNJQivZ2vN0tpUSdSeNAxuVmFO3xGSG5vLvxo2IxDMAz/XOxBl263/boObeIgP3phCyMlZr5jRVT07k8MsBAK8gwxPJ8ERSmChMTs/d7Apl3oJa61TAMJd2Vg6380ow3wrACqQ0IbgLn2S3RcYTiCLPy9R+hYNkdt29/vvEj0g0Yg/crKIJAjT92x+K/1hZDgQdrSxpcLhZ9M7MZjX1vz33cvXKP9egB0W5BfydOw2f79ysLZhUryx/RcEEmgo76BhgBm/4Br/C2Yo+lPBIgH9UyY6bJ/d04C4cmjRTjDB4ytoVtuyOwffTLDCQia0cd76/4ieK4bDKTx4upB56nSEymWkahHe3pv/FXz8V3m3xHxeRWWPLaCzq+v7VBvu84Qu5Dyb6dxt/X7PHEvGPETf9N/Je7tj8bORViIkGyaif2KmRcyNyL/dskm9z+LovotwsswME6IF8d2jGVGQvSPxX5HPXpKuKKHn1Y+dbtcJIPW9D7GOBWjVwXx4KH21KmWbF386Rq4GVWBOrHyGNy45zBeiyirqiZ3D5gUMFq9BtVyV6/QHVdTq1xnLSHIo8IBfqiXdzB9vNMvkHVazkrlN3dVZU/kbu9rjNp2BQ8z0KxyPX0uuAXbUqLQsZHU9/FMWcYIndIO/Yb804yHlWP7W9BbH3nDS06xHe3iM29kabaWmBYptW4F/3qGpKIMXCbUM7hcOaOr3MKs8vGlBe5k1/MD4MjQZGY/WLTsn3FRZaRlVI1Psvr9j+z4z5/249BzlDkJVcTGcz8Qq9tPIglk=,iv:zdHekgC972KKB8987V7yHBfu5ORzwOLZUnlDyJ6qR2Q=,tag:QAZUETcox8Dd1tErrLcW3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGVDQXZva3Z3YlROZFhj
            SWhRaWRwSnVHMWlSSDIwMW1OZ011YmUyZTN3CnBJTnZJRWkvWUQxOWtwVm1MTGdB
            Z05VSTdyck5iejQxakZjakVEVEorS2sKLS0tIDQ3VXhLcW5JQUF0V2FUZ0JuZG91
            RVdoT0g1aGV3d1IrL2ZxdzBKTWVhM28Kf6xeA1sBFjC8d1nCFVHYxkRndR8pN0z4
            Sg1XvK4loM8956wjbfaA4NzQmejnuP2oGxn6ICyESE5cxDFjEi8Inw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:P7txWrASQTpXhdX650SJQaqm30mp8o6iqW841UAcwaM5bRPiaYJaaWCsvY0abFc7Kdu8tK1q8+uJgDraS5G/O5RtNrcdgTxmn+xFkLrGctRrkD/NDEKPdr+7Nk4I4osBcesHHk71Rc0BSW9FxJDlnAk6ahKTMWJB3TN9iI2b7bI=,iv:3d6hq8DPFO6SAqbBOX6gfmZ3HtBJwUjE3ZhaTBxHX60=,tag:Y31VSh6yuRoUYa7PMwHs4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: v1
kind: Service
metadata:
    name: dex
    namespace: dex
spec:
    type: ClusterIP
    ports:
        - name: dex
          port: 5556
          protocol: TCP
          targetPort: 5556
    selector:
        app: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGVDQXZva3Z3YlROZFhj
            SWhRaWRwSnVHMWlSSDIwMW1OZ011YmUyZTN3CnBJTnZJRWkvWUQxOWtwVm1MTGdB
            Z05VSTdyck5iejQxakZjakVEVEorS2sKLS0tIDQ3VXhLcW5JQUF0V2FUZ0JuZG91
            RVdoT0g1aGV3d1IrL2ZxdzBKTWVhM28Kf6xeA1sBFjC8d1nCFVHYxkRndR8pN0z4
            Sg1XvK4loM8956wjbfaA4NzQmejnuP2oGxn6ICyESE5cxDFjEi8Inw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:P7txWrASQTpXhdX650SJQaqm30mp8o6iqW841UAcwaM5bRPiaYJaaWCsvY0abFc7Kdu8tK1q8+uJgDraS5G/O5RtNrcdgTxmn+xFkLrGctRrkD/NDEKPdr+7Nk4I4osBcesHHk71Rc0BSW9FxJDlnAk6ahKTMWJB3TN9iI2b7bI=,iv:3d6hq8DPFO6SAqbBOX6gfmZ3HtBJwUjE3ZhaTBxHX60=,tag:Y31VSh6yuRoUYa7PMwHs4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app: dex
    name: dex
    namespace: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGVDQXZva3Z3YlROZFhj
            SWhRaWRwSnVHMWlSSDIwMW1OZ011YmUyZTN3CnBJTnZJRWkvWUQxOWtwVm1MTGdB
            Z05VSTdyck5iejQxakZjakVEVEorS2sKLS0tIDQ3VXhLcW5JQUF0V2FUZ0JuZG91
            RVdoT0g1aGV3d1IrL2ZxdzBKTWVhM28Kf6xeA1sBFjC8d1nCFVHYxkRndR8pN0z4
            Sg1XvK4loM8956wjbfaA4NzQmejnuP2oGxn6ICyESE5cxDFjEi8Inw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:P7txWrASQTpXhdX650SJQaqm30mp8o6iqW841UAcwaM5bRPiaYJaaWCsvY0abFc7Kdu8tK1q8+uJgDraS5G/O5RtNrcdgTxmn+xFkLrGctRrkD/NDEKPdr+7Nk4I4osBcesHHk71Rc0BSW9FxJDlnAk6ahKTMWJB3TN9iI2b7bI=,iv:3d6hq8DPFO6SAqbBOX6gfmZ3HtBJwUjE3ZhaTBxHX60=,tag:Y31VSh6yuRoUYa7PMwHs4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: dex
rules:
    - apiGroups:
        - dex.coreos.com
      resources:
        - '*'
      verbs:
        - '*'
    - apiGroups:
        - apiextensions.k8s.io
      resources:
        - customresourcedefinitions
      verbs:
        - create
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGVDQXZva3Z3YlROZFhj
            SWhRaWRwSnVHMWlSSDIwMW1OZ011YmUyZTN3CnBJTnZJRWkvWUQxOWtwVm1MTGdB
            Z05VSTdyck5iejQxakZjakVEVEorS2sKLS0tIDQ3VXhLcW5JQUF0V2FUZ0JuZG91
            RVdoT0g1aGV3d1IrL2ZxdzBKTWVhM28Kf6xeA1sBFjC8d1nCFVHYxkRndR8pN0z4
            Sg1XvK4loM8956wjbfaA4NzQmejnuP2oGxn6ICyESE5cxDFjEi8Inw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:P7txWrASQTpXhdX650SJQaqm30mp8o6iqW841UAcwaM5bRPiaYJaaWCsvY0abFc7Kdu8tK1q8+uJgDraS5G/O5RtNrcdgTxmn+xFkLrGctRrkD/NDEKPdr+7Nk4I4osBcesHHk71Rc0BSW9FxJDlnAk6ahKTMWJB3TN9iI2b7bI=,iv:3d6hq8DPFO6SAqbBOX6gfmZ3HtBJwUjE3ZhaTBxHX60=,tag:Y31VSh6yuRoUYa7PMwHs4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: dex
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: dex
subjects:
    - kind: ServiceAccount
      name: dex
      namespace: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGVDQXZva3Z3YlROZFhj
            SWhRaWRwSnVHMWlSSDIwMW1OZ011YmUyZTN3CnBJTnZJRWkvWUQxOWtwVm1MTGdB
            Z05VSTdyck5iejQxakZjakVEVEorS2sKLS0tIDQ3VXhLcW5JQUF0V2FUZ0JuZG91
            RVdoT0g1aGV3d1IrL2ZxdzBKTWVhM28Kf6xeA1sBFjC8d1nCFVHYxkRndR8pN0z4
            Sg1XvK4loM8956wjbfaA4NzQmejnuP2oGxn6ICyESE5cxDFjEi8Inw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T00:52:21Z"
    mac: ENC[AES256_GCM,data:P7txWrASQTpXhdX650SJQaqm30mp8o6iqW841UAcwaM5bRPiaYJaaWCsvY0abFc7Kdu8tK1q8+uJgDraS5G/O5RtNrcdgTxmn+xFkLrGctRrkD/NDEKPdr+7Nk4I4osBcesHHk71Rc0BSW9FxJDlnAk6ahKTMWJB3TN9iI2b7bI=,iv:3d6hq8DPFO6SAqbBOX6gfmZ3HtBJwUjE3ZhaTBxHX60=,tag:Y31VSh6yuRoUYa7PMwHs4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
