apiVersion: v1
kind: Namespace
metadata:
    name: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2F6TXI2ZXd6a0NzYko1
            OTlGd0NzdjZURmVMbWN4SDVpN1VHWjBzTEFRCnI5aTRPaW1MNzVlMll3ak1NbnNX
            NDkwTndWbTZOc3ZVcFdnNnkyTjNLU28KLS0tIDVGbStwdkpZME5WMG56bjlqd2NN
            VEgvY1ptU2swRDBGejBjRGNkZUNVcG8KICdDWWoA2NKewgU+xXckxu9wFQ23n10a
            UAQXDjw4c7kZLXlol/VfX80N1t1Or/AFXXTaUsy9oV466nRcZEYIHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T11:25:01Z"
    mac: ENC[AES256_GCM,data:LrFJ1/gJoSQ5oIncQBeRlVUcGMEzdIZ5QO/hG9WFv1APJk/VH9t81KEh4z6OtTLDZfapHGlNBelTtmoMgohcIm//AWGPsUO3hbshRCBRjgs1OsDqCtzR43usCQnQpD+hcK7fNOE1uTG0Kdm2BnkK1eVxmPRKmdOUK2S6WjuhUrI=,iv:UKrnf2XWcg18PLWDJMnaszz+6O4g6ePjdlxa5aa5pMM=,tag:QlS13vzpoL3OQrVvBVBE7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: dex
    name: dex
    namespace: dex
spec:
    replicas: 3
    selector:
        matchLabels:
            app: dex
    template:
        metadata:
            labels:
                app: dex
        spec:
            serviceAccountName: dex
            containers:
                - image: ghcr.io/dexidp/dex:v2.30.0
                  name: dex
                  command:
                    - /usr/local/bin/dex
                    - serve
                    - /etc/dex/cfg/config.yaml
                  ports:
                    - name: https
                      containerPort: 5556
                  volumeMounts:
                    - name: config
                      mountPath: /etc/dex/cfg
                  env:
                    - name: GITHUB_CLIENT_ID
                      valueFrom:
                        secretKeyRef:
                            name: github-client
                            key: client-id
                    - name: GITHUB_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                            name: github-client
                            key: client-secret
                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: 5556
                        scheme: HTTP
            volumes:
                - name: config
                  secret:
                    secretName: dex
                    items:
                        - key: config.yaml
                          path: config.yaml
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2F6TXI2ZXd6a0NzYko1
            OTlGd0NzdjZURmVMbWN4SDVpN1VHWjBzTEFRCnI5aTRPaW1MNzVlMll3ak1NbnNX
            NDkwTndWbTZOc3ZVcFdnNnkyTjNLU28KLS0tIDVGbStwdkpZME5WMG56bjlqd2NN
            VEgvY1ptU2swRDBGejBjRGNkZUNVcG8KICdDWWoA2NKewgU+xXckxu9wFQ23n10a
            UAQXDjw4c7kZLXlol/VfX80N1t1Or/AFXXTaUsy9oV466nRcZEYIHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T11:25:01Z"
    mac: ENC[AES256_GCM,data:LrFJ1/gJoSQ5oIncQBeRlVUcGMEzdIZ5QO/hG9WFv1APJk/VH9t81KEh4z6OtTLDZfapHGlNBelTtmoMgohcIm//AWGPsUO3hbshRCBRjgs1OsDqCtzR43usCQnQpD+hcK7fNOE1uTG0Kdm2BnkK1eVxmPRKmdOUK2S6WjuhUrI=,iv:UKrnf2XWcg18PLWDJMnaszz+6O4g6ePjdlxa5aa5pMM=,tag:QlS13vzpoL3OQrVvBVBE7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
kind: Secret
apiVersion: v1
metadata:
    name: dex
    namespace: dex
    annotations:
        kapp.k14s.io/versioned: ""
data:
    config.yaml: ENC[AES256_GCM,data:x3InDFejSmxQLBf/er6DFwfBcue2VuAVbJgaXKKfn4XazsTzVwc4D342eqhe1JR5edJBcHt0/wmVejqZKb/BATgrxNO/fNiNFbtjMVl0GAbIV0gmLTALq7aicHijb3r3QDwGTD41SJKopW6QQZNYXmMhSyuogbEMSFGc/fKQ4nvr7dYdO1WPeyRzropfGsCjrOnpipVBnW7H6sYmdU7tfDhwhCNs5y5EdYAEGCxT13EzR1wrdlGUzPIJbXC6UugZEKnhnvWBOqUVxURDRA78n0+fi/jM9+JUr5XIkAb+2Fk4jUOu6YkftvGa+8wnkvbYjfOjhIrrLnXsQ/UCkyEry3vrZ3vJ6Ky9++aQFtYz4zedF9k8DhRkF4tvjxGh+R56sRBpPdzxTTJ8j8XDWjstgJ3OcR5794iFVlcUeK4HiQzC92oFLEP6YSKgoIyyjKpF7nqn1JGM276FnTjkoxYVy0GTp82AITrOXFDmaZpYil7+DQX5QPqfS5BXuHSQyRdhMnhIhJUoLhDvpQCzblXhjAyDyX+qrsdH7WpdrYyO8AWjm0ujNyHYQKGAKMhaq5usIDUfokhMksQJWxTEB8CNjOOEnFjI+A9g/wvayFqB8llzz8lAxlSbQLRzeUMvIxwn3t1bCUrml9ytCV9KHShYtFRlQBKSLbjSacXNSb45P4e6tDYrCGUMfDOXRvB/0T4CGuBqRq2DGSZEfkkCKKlHz1idC09X270HYbXujetIQ+m2p6T2eI5AYemf/FLS+t3nL1MPNYUmEj4qroAznrTXhmFX7YCeccDEH+IjaEzWYGlcPPG55oToHnkZWvdkbTS/89ZSmNtdMXtKnwSAMy6vnbFgdgeYmkCcccbVtZLX94Pnvcn+U5qK4u6ubtFFdHvicjRkhLFmQRc4IUS7TyW0fXNZEaDgGcmKf9IUvRqJZ286+0sODZas3/S3pzLR2r4Eyi+TsmJY4vo=,iv:EFnGcUqm9zkOnyIE1GA65ThGil8VUoc29HFOBdKSV2g=,tag:gqvp4/DMmOzM59RqjSgqlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2F6TXI2ZXd6a0NzYko1
            OTlGd0NzdjZURmVMbWN4SDVpN1VHWjBzTEFRCnI5aTRPaW1MNzVlMll3ak1NbnNX
            NDkwTndWbTZOc3ZVcFdnNnkyTjNLU28KLS0tIDVGbStwdkpZME5WMG56bjlqd2NN
            VEgvY1ptU2swRDBGejBjRGNkZUNVcG8KICdDWWoA2NKewgU+xXckxu9wFQ23n10a
            UAQXDjw4c7kZLXlol/VfX80N1t1Or/AFXXTaUsy9oV466nRcZEYIHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T11:25:01Z"
    mac: ENC[AES256_GCM,data:LrFJ1/gJoSQ5oIncQBeRlVUcGMEzdIZ5QO/hG9WFv1APJk/VH9t81KEh4z6OtTLDZfapHGlNBelTtmoMgohcIm//AWGPsUO3hbshRCBRjgs1OsDqCtzR43usCQnQpD+hcK7fNOE1uTG0Kdm2BnkK1eVxmPRKmdOUK2S6WjuhUrI=,iv:UKrnf2XWcg18PLWDJMnaszz+6O4g6ePjdlxa5aa5pMM=,tag:QlS13vzpoL3OQrVvBVBE7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: v1
kind: Service
metadata:
    name: dex
    namespace: dex
spec:
    type: ClusterIP
    ports:
        - name: dex
          port: 5556
          protocol: TCP
          targetPort: 5556
    selector:
        app: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2F6TXI2ZXd6a0NzYko1
            OTlGd0NzdjZURmVMbWN4SDVpN1VHWjBzTEFRCnI5aTRPaW1MNzVlMll3ak1NbnNX
            NDkwTndWbTZOc3ZVcFdnNnkyTjNLU28KLS0tIDVGbStwdkpZME5WMG56bjlqd2NN
            VEgvY1ptU2swRDBGejBjRGNkZUNVcG8KICdDWWoA2NKewgU+xXckxu9wFQ23n10a
            UAQXDjw4c7kZLXlol/VfX80N1t1Or/AFXXTaUsy9oV466nRcZEYIHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T11:25:01Z"
    mac: ENC[AES256_GCM,data:LrFJ1/gJoSQ5oIncQBeRlVUcGMEzdIZ5QO/hG9WFv1APJk/VH9t81KEh4z6OtTLDZfapHGlNBelTtmoMgohcIm//AWGPsUO3hbshRCBRjgs1OsDqCtzR43usCQnQpD+hcK7fNOE1uTG0Kdm2BnkK1eVxmPRKmdOUK2S6WjuhUrI=,iv:UKrnf2XWcg18PLWDJMnaszz+6O4g6ePjdlxa5aa5pMM=,tag:QlS13vzpoL3OQrVvBVBE7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app: dex
    name: dex
    namespace: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2F6TXI2ZXd6a0NzYko1
            OTlGd0NzdjZURmVMbWN4SDVpN1VHWjBzTEFRCnI5aTRPaW1MNzVlMll3ak1NbnNX
            NDkwTndWbTZOc3ZVcFdnNnkyTjNLU28KLS0tIDVGbStwdkpZME5WMG56bjlqd2NN
            VEgvY1ptU2swRDBGejBjRGNkZUNVcG8KICdDWWoA2NKewgU+xXckxu9wFQ23n10a
            UAQXDjw4c7kZLXlol/VfX80N1t1Or/AFXXTaUsy9oV466nRcZEYIHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T11:25:01Z"
    mac: ENC[AES256_GCM,data:LrFJ1/gJoSQ5oIncQBeRlVUcGMEzdIZ5QO/hG9WFv1APJk/VH9t81KEh4z6OtTLDZfapHGlNBelTtmoMgohcIm//AWGPsUO3hbshRCBRjgs1OsDqCtzR43usCQnQpD+hcK7fNOE1uTG0Kdm2BnkK1eVxmPRKmdOUK2S6WjuhUrI=,iv:UKrnf2XWcg18PLWDJMnaszz+6O4g6ePjdlxa5aa5pMM=,tag:QlS13vzpoL3OQrVvBVBE7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: dex
rules:
    - apiGroups:
        - dex.coreos.com
      resources:
        - '*'
      verbs:
        - '*'
    - apiGroups:
        - apiextensions.k8s.io
      resources:
        - customresourcedefinitions
      verbs:
        - create
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2F6TXI2ZXd6a0NzYko1
            OTlGd0NzdjZURmVMbWN4SDVpN1VHWjBzTEFRCnI5aTRPaW1MNzVlMll3ak1NbnNX
            NDkwTndWbTZOc3ZVcFdnNnkyTjNLU28KLS0tIDVGbStwdkpZME5WMG56bjlqd2NN
            VEgvY1ptU2swRDBGejBjRGNkZUNVcG8KICdDWWoA2NKewgU+xXckxu9wFQ23n10a
            UAQXDjw4c7kZLXlol/VfX80N1t1Or/AFXXTaUsy9oV466nRcZEYIHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T11:25:01Z"
    mac: ENC[AES256_GCM,data:LrFJ1/gJoSQ5oIncQBeRlVUcGMEzdIZ5QO/hG9WFv1APJk/VH9t81KEh4z6OtTLDZfapHGlNBelTtmoMgohcIm//AWGPsUO3hbshRCBRjgs1OsDqCtzR43usCQnQpD+hcK7fNOE1uTG0Kdm2BnkK1eVxmPRKmdOUK2S6WjuhUrI=,iv:UKrnf2XWcg18PLWDJMnaszz+6O4g6ePjdlxa5aa5pMM=,tag:QlS13vzpoL3OQrVvBVBE7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: dex
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: dex
subjects:
    - kind: ServiceAccount
      name: dex
      namespace: dex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e25ew05v62a720vhsetzrhalehzpsv6l6c5usw2mn4lley85ssnsajz2v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2F6TXI2ZXd6a0NzYko1
            OTlGd0NzdjZURmVMbWN4SDVpN1VHWjBzTEFRCnI5aTRPaW1MNzVlMll3ak1NbnNX
            NDkwTndWbTZOc3ZVcFdnNnkyTjNLU28KLS0tIDVGbStwdkpZME5WMG56bjlqd2NN
            VEgvY1ptU2swRDBGejBjRGNkZUNVcG8KICdDWWoA2NKewgU+xXckxu9wFQ23n10a
            UAQXDjw4c7kZLXlol/VfX80N1t1Or/AFXXTaUsy9oV466nRcZEYIHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T11:25:01Z"
    mac: ENC[AES256_GCM,data:LrFJ1/gJoSQ5oIncQBeRlVUcGMEzdIZ5QO/hG9WFv1APJk/VH9t81KEh4z6OtTLDZfapHGlNBelTtmoMgohcIm//AWGPsUO3hbshRCBRjgs1OsDqCtzR43usCQnQpD+hcK7fNOE1uTG0Kdm2BnkK1eVxmPRKmdOUK2S6WjuhUrI=,iv:UKrnf2XWcg18PLWDJMnaszz+6O4g6ePjdlxa5aa5pMM=,tag:QlS13vzpoL3OQrVvBVBE7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*client.secret.*)$
    version: 3.7.2
