#@ load("@ytt:data", "data")

#@ if data.values.dex_tls:
---
apiVersion: v1
kind: Secret
metadata:
  name: tls
  namespace: dex
type: kubernetes.io/tls
stringData:
  tls.crt: #@ data.values.dex_tls.crt
  tls.key: #@ data.values.dex_tls.key
#@ end
